// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace ComoSecondModel
{
    public partial class ComosecondContext : DbContext
    {
        public ComosecondContext()
        {
        }

        public ComosecondContext(DbContextOptions<ComosecondContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Projet> Projet { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "French_CI_AS");

            modelBuilder.Entity<Projet>(entity =>
            {
                entity.Property(e => e.Colaborateur).IsUnicode(false);

                entity.Property(e => e.Descriptif).IsUnicode(false);

                entity.Property(e => e.Title).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}