// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ComoSecondModel
{
    public partial class Projet
    {
        [Key]
        public int Id { get; set; }
        [StringLength(200)]
        public string Title { get; set; }
        [StringLength(200)]
        public string Colaborateur { get; set; }
        public byte[] Document { get; set; }
        [StringLength(500)]
        public string Descriptif { get; set; }
        public byte[] Image { get; set; }
    }
}